### ISSUE TITLE
add unit to in total_volume_gross_of_class_1 var definition 

### ISSUE THREAD

**Issue by andrecastro0o** [ruisdael-observatory/disdroDL#14]
Original comment from @mschleiss https://github.com/ruisdael-observatory/disdroDL/issues/2#issuecomment-2290918916:

> Issue 3: Variable: total_volume_gross_of_class_1:long_name = "Total volume (gross) of class 1 (unitless)" is given as uniteless. However, volume should have a unit. Same comment for all the other total_volume_gross variables. Please check the unit of all these variables and include it in the metadata description.

Merge to branch [https://github.com/ruisdael-observatory/disdroDL/tree/0.3.2](https://github.com/ruisdael-observatory/disdroDL/tree/0.3.2)

**Comment by andrecastro0o** [comment]
include links to Manufacturer Documentation  for 
* Thies Clima LPM - https://www.thiesclima.com/db/dnl/5.4110.xx.x00_Laser_Precipitation_Monitor_eng.pdf
* Parsivel - https://www.ott.com/download/operating-instructions-present-weather-sensor-ott-parsivel2-with-screen-heating-3/

**Comment by andrecastro0o** [comment]
@mschleiss the [Thies documentation](https://www.thiesclima.com/db/dnl/5.4110.xx.x00_Laser_Precipitation_Monitor_eng.pdf) only includes one reference to  "total volume (gross) of class 1" or field 64, in page 48 , with no info on its units

Also google search did not help 

![Screenshot 2024-08-20 at 14-29-25 LNM 5 4110 xx x0 - 5 4110 xx x00_Laser_Precipitation_Monitor_eng pdf](https://github.com/user-attachments/assets/247c7de2-cf36-439d-a57d-06597eeff669)

**Comment by mschleiss** [comment]
Comment *6 on page 51/72 of the documentation says that these are: "internal data (raw values)". But that does not help, since the total number of particles in each class is also considered to be internal data. I suggest to leave it as is and add a comment: "internal data with unknown unit".

**Comment by andrecastro0o** [comment]
previous comment from @mschleiss  implemented in https://github.com/ruisdael-observatory/disdroDL/pull/25/commits/461cf4d4164816f85b9ed4fd2866737417a2db81
