### ISSUE TITLE
Thies vars as integers

### ISSUE THREAD

**Issue by andrecastro0o** [ruisdael-observatory/disdroDL#26]
Variables that could be encoded as an **unsigned** 32 bit integer instead of a float:
- visiblity

Variables that could be encoded as **unsigned** 16 bit integer instead of a float:
- mean_value_laser_current
- control_voltage
- optical_control_output

Variables that could be encoded as an **unsigned** 8-bit integer:
- measurement quality
- current_heating_laser_head
- current_heating_receiver_head

Variables that could be encoded as a **signed** 8-bit integer:
- interior_temperature
- temperature_laser_driver

Not sure how much control you have over the type of integer. At least, we could use 32 bit integers for most of the variables above and 8 bit integers for the variables whose values range between 0-100.

_Originally posted by @mschleiss in https://github.com/ruisdael-observatory/disdroDL/issues/2#issuecomment-2310271247_

**Comment by andrecastro0o** [comment]
originally posted in https://github.com/ruisdael-observatory/disdroDL/issues/2#issuecomment-2312523374

Variables that could be encoded as an unsigned 32 bit integer instead of a float:
* visibility:
   * field number: 18
   * example: `18:99999`
   * needs conversion: UNSURE

Variables that could be encoded as unsigned 16 bit integer instead of a float:
* mean_value_laser_current:
   * field number: 40
   * example: 40:1778
   * needs conversion:  NO
* control_voltage:
   * field number: 41
   * example:  41:4011
   * needs conversion:  NO
* optical_control_output
   * field number: 42
   * example:  42:2772
   * needs conversion:  NO

Variables that could be encoded as an unsigned 8-bit integer:
* measurement_quality
   * field number: 20
   * example:  22:0
   * needs conversion:  NO
* current_heating_laser_head
   * field number: 44
   * example:  `44:028;`
   * needs conversion:  NO
* current_heating_receiver_head
   * field number: 45
   * example: `45:034`
   * needs conversion:  NO
   
Variables that could be encoded as a signed 8-bit integer:
* interior_temperature
   * field number: 38
   * example: `38:+33`
   * needs conversion:  NO
* temperature_of_laser_driver
   * field number: 39
   * example: `39:37`
   * needs conversion:  NO

**Comment by andrecastro0o** [comment]
@mschleiss the change of dtypes in vars (see changes in https://github.com/ruisdael-observatory/disdroDL/pull/27/files) is not going  that smoothly. The tests are failing (see https://github.com/ruisdael-observatory/disdroDL/actions/runs/10579046264/job/29310540581?pr=27) and I am struggling to understand the cause for it.

I will need to dig deeper onto this if we want to implement these dtype changes

**Comment by mschleiss** [comment]
@andrecastro0o could be that the fill values we use for the variables are out of range.

**Comment by andrecastro0o** [comment]
> @andrecastro0o could be that the fill values we use for the variables are out of range.

that might very well be it. I will try that.

**Comment by andrecastro0o** [comment]
@mschleiss so the issue indeed seems to be related to the fill value in [netCDF.py#L348](https://github.com/ruisdael-observatory/disdroDL/blob/41f1fd0c9e778314df1c4ae819a913da70aa3bcc/modules/netCDF.py#L348) `fill_val = -999`

I don't know about signed/unsigned values, but I learned that unsigned integers cannot represent negative values (https://dev.to/aidiri/signed-vs-unsigned-bit-integers-what-does-it-mean-and-what-s-the-difference-41a3) so we might need to use signed ones.

I will try to implement and test :crossed_fingers:

**Comment by mschleiss** [comment]
Sounds reasonable. Indeed, due to the way we decided to encode fill values and/or missing values, it might be better to go for unsigned integers (16 or 32 bit) to avoid having to change too much in the rest of the code.

**Comment by andrecastro0o** [comment]
merged into dev branc 0.3.3 https://github.com/ruisdael-observatory/disdroDL/pull/27
